import Head from "next/head";
import Navbar from "./navbar";
import Footer from "./footer";
import { Context } from "../context/context";
import { useContext } from "react";

import DiaphragmAnimation from "./diaphragmAnimation";

const Layout = ({ children }) => {
  const { shutterEffect } = useContext(Context);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css2?family=Arizonia&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <header>
        <Navbar />
      </header>
      <main>
        {shutterEffect && <DiaphragmAnimation />}

        {children}
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
};

export default Layout;
